### ISSUE TITLE
Errors during build and installation process

### ISSUE THREAD

**Issue by BeomBeom2** [LiJiangnanBit/path_optimizer#15]
Hello, First of all, sorry for being a beginner. I did install dependencies and build tap as described in the readme. but the third command
sudo bash path_optimizer/scripts/install_deps.sh
After hitting , I got the following error: I ignored it and even tried roslaunch, but the image file was not loaded.
what could i do?

![image](https://user-images.githubusercontent.com/62642155/136655405-4e283ed0-ba3b-4814-bf9e-dd47eda72d02.png)

### while I did catkin_make

![image](https://user-images.githubusercontent.com/62642155/136655682-842a03f8-f3d3-46ad-a878-fde35e669a90.png)

**Comment by LiJiangnanBit** [comment]
Hi，please try "catkin build" instead of "catkin_make". If the same error occurs, follow https://github.com/ANYbotics/grid_map to install this lib manually. :)

**Comment by LiJiangnanBit** [comment]
The first pic suggests that some tests of IPOPT failed. I'm not sure if this matters.

**Comment by BeomBeom2** [comment]
Thank you for answer. I commanded catkin_build as you said and got the same error.
So as a second alternative, I tried to install the package myself, but this grid_map_costmap_2d was not installed.

![image](https://user-images.githubusercontent.com/62642155/136659690-930dca54-f3f3-422a-a56b-4cd39405111e.png)

So I looked for any errors in [this article](https://github.com/ANYbotics/grid_map/issues/302), and there was advice, so I removed only the package and tried catkin_build, but it didn't work either. what am i missing...

**Comment by LiJiangnanBit** [comment]
Did you run "catkin build path_optimizer"? This package only depends on grid_map_ros, not grid_map_costmap_2d

**Comment by LiJiangnanBit** [comment]
Also, i did not test this package on ubuntu 18.04

**Comment by BeomBeom2** [comment]
oh i see, maybe the version does not match, so the dependent lib was not installed properly in the process of install_deps.sh.
so, i did install ros_viz_tools, tinyspline_ros by hand

#### Where can I determine which package is missing from this error?

![image](https://user-images.githubusercontent.com/62642155/136680271-49e7dd12-327e-4664-8deb-c3df19ad938b.png)


 I do have a another question. Can you implement self-driving cars using your package? 
``` I'm actually looking for a dynamic path program because of a school team project.```

**Comment by BeomBeom2** [comment]
> 또한 우분투 18.04에서 이 패키지를 테스트하지 않았습니다.

oh i see, maybe the version does not match, so the dependent lib was not installed properly in the process of install_deps.sh.
so, i did install ros_viz_tools, tinyspline_ros by hand

#### Where can I determine which package is missing from this error?

![image](https://user-images.githubusercontent.com/62642155/136680271-49e7dd12-327e-4664-8deb-c3df19ad938b.png)


 I do have a another question. Can you implement self-driving cars using your package? 
``` I'm actually looking for a dynamic path program because of a school team project.```
