### ISSUE TITLE
Is there any reference for tension_smoother_2?

### ISSUE THREAD

**Issue by k0suke-murakami** [LiJiangnanBit/path_optimizer#7]
The repo has new smoothing method called `tension_smoother_2`.
Possibly the method mentioned in this [issue](https://github.com/LiJiangnanBit/path_optimizer/issues/6#issuecomment-630169217)?

Do you have any references(possibly paper?) for the new method?

**Comment by LiJiangnanBit** [comment]
No, it's just a simple thought. The smoothed points are represented by (x_i, y_i, theta_i),  and the curvature k is the control variable. They are linearized around the reference points (search result). A simple optimization problem is formulated, minimizing the distance between these points and the reference points, the accumulated curvature, etc.
